# Site settings
title: Praveer's blog
description: "A place to post the thoughts that I want to share"
url: "http://praveer13.github.io"
author:
  name: "Praveer N"
  url: "http://praveer13.github.io"

# Build settings
baseurl: /blog/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.0.1"
